aledar_enabled: true
aledar_map: "CLASSIC"
aura_enabled: true
aura_map1: "OCEAN"
aura_map2: "SWAMP"
aura_map3: "CRYSTAL"
avos_enabled: true
avos_map: "CORKUS"
excavation_enabled: true
excavation_map: "JUNGLE"
nesaak_enabled: true
nesaak_map: "VALLEY_TOWN"
nether_enabled: true
nether_map: "NETHER"
prof_enabled: true
prof_map: "FLATLAND"
sky_enabled: true
sky_map: "SKY"